language: ruby
rvm:
  - jruby
  - ruby-head
  - 2.1
  - 2.0.0
  - 1.9.3
  - rbx
script:
  - NOEXEC_DISABLE=1 rake
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
